# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import frontend_pb2 as frontend__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/frontend.Greeter/SayHello',
        request_serializer=frontend__pb2.HelloRequest.SerializeToString,
        response_deserializer=frontend__pb2.HelloReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=frontend__pb2.HelloRequest.FromString,
          response_serializer=frontend__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'frontend.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
