# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Messages_pb2 as Messages__pb2


class MessengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDump = channel.unary_unary(
        '/Messenger/GetDump',
        request_serializer=Messages__pb2.Date2.SerializeToString,
        response_deserializer=Messages__pb2.Dump.FromString,
        )
    self.HasUpdate = channel.unary_unary(
        '/Messenger/HasUpdate',
        request_serializer=Messages__pb2.Date2.SerializeToString,
        response_deserializer=Messages__pb2.UpdateStatus.FromString,
        )


class MessengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDump(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDump': grpc.unary_unary_rpc_method_handler(
          servicer.GetDump,
          request_deserializer=Messages__pb2.Date2.FromString,
          response_serializer=Messages__pb2.Dump.SerializeToString,
      ),
      'HasUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.HasUpdate,
          request_deserializer=Messages__pb2.Date2.FromString,
          response_serializer=Messages__pb2.UpdateStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Messenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
